Name: Tests
on:
  push:
jobs:
  test:
    name: norminette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      - name: Run Norminette.
        run: make norm
